---
version: 2
jobs:
  setup:
    working_directory: ~/workspace
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/workspace/node_modules
  lint:
    working_directory: ~/workspace
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:10
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: "Lint"
          command: npm run lint-js
  test:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: Run test
          command: npm run test
workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
