version: 2 
jobs:       
  build:
    docker:
      - image: circleci/node:8.14
      - image: mongo:3.6
    steps:
      - checkout
      - run:
          name: Hello World TEST
          command: "npm run test"
workflows:
  version: 2
  build_test:
    jobs:
      - build
